version: "2"
services:
  zookeeper:
    image: 'registry.aliyuncs.com/acs-sample/zookeeper:3.4.8'
    ports:
      - 2181:2181    
  producer:
    image: 'juixtu/service-producer:v1'
    environment:
      - ZOOKEEPER_SERVER=[zk地址]
      - DUBBO_IP_TO_REGISTRY=[需要注册的地址]
    ports:
      - 20880:20880
  consumer:
    image: 'juixtu/service-consumer:v1'
    environment:
      - ZOOKEEPER_SERVER=[zk地址]
      - DUBBO_IP_TO_REGISTRY=[需要注册的地址]
      - SERVER_PORT=8899
    ports:
      - 8899:8899
