apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: {{ .Values.namespace }}
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8899"
        - name: ZOOKEEPER_SERVER
          value: {{ .Values.zookeeper }}
        - name: DUBBO_IP_TO_REGISTRY
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        image: juixtu/service-consumer:v1
        name: consumer
        ports:
        - containerPort: 8899
      restartPolicy: Always
