apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer
  name: producer
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - env:
        - name: ZOOKEEPER_SERVER
          value: {{ .Values.zookeeper }}
        - name: DUBBO_IP_TO_REGISTRY
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP     
        image: juixtu/service-producer:v1
        name: producer
        ports:
        - containerPort: 20880      
      restartPolicy: Always